apiVersion: v1
kind: ConfigMap
metadata:
  name: conf
data:
  nginx.conf: |
    events {
      worker_connections  4096;  ## Default: 1024
    }

    http {
    upstream myapp {
        server nodeapp:80;
    }

    server { 
    listen 80;
    server_name frontend;
    
    location / {
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-NginX-Proxy true;
      proxy_pass http://myapp;
      proxy_ssl_session_reuse off;
      proxy_set_header Host $http_host;
      proxy_cache_bypass $http_upgrade;
      proxy_redirect off;
      }
      }
    }
