# apiVersion: v1
# kind: Pod
# metadata:
#   name: example
#   labels:
#     app: example
# spec:
#   containers:
#   - name: web
#     image: nginx:latest
#     ports:
#     - containerPort: 80
#     volumeMounts:
#       - name: nginx-file
#         mountPath: /etc/nginx/nginx.conf
#         subPath: nginx.conf
#   volumes:
#   - name: nginx-file
#     configMap:
#       name: conf

# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: nodeapp
    spec: 
      terminationGracePeriodSeconds: 1
      containers:
      - name: nodeapp
        image: nginxdemos/hello:latest

# ---

# apiVersion: v1
# kind: Pod
# metadata:
#   name: nodeapp
#   labels:
#     app: nodeapp
# spec:
#   containers:
#   - name: nodeapp
#     image: nginxdemos/hello:latest

---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: nodeapp

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: hello-front
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 80
#   selector:
#     app: example

--- 
# https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: nodeapp-rule
#   annotations:
#     kubernetes.io/ingress.class: nginx
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /jonathan
#         pathType: Prefix
#         backend:
#           service:
#             name: nodeapp
#             port:
#               number: 80